DATA:
  data_path: "/raid/candi/yiwen/data/multiorgan_final"  # path to folder including institution.txt and data
  fold: 1
  resolution: [ 0.75, 0.75, 2.5 ]
  patch_size: [96, 96, 16]
  size: [ 256, 256, 40 ]
  organ_list: ["BladderMask", "BoneMask", "ObdInternMask", "TZ", "CG", "RectumMask", "SV", "NVB"]
  semi_supervision: False
  label_ratio: 1.0

MODEL:
  input: "patch"
  multi_head: False
  reg: False
