DATA:
  data_path: "/raid/candi/yiwen/data/multiorgan_final"  # path to folder including institution.txt and data
  fold: 1
  resolution: [ 0.75, 0.75, 2.5 ]
  size: [ 256, 256, 40 ]
  organ_list: ["BladderMask", "BoneMask", "ObdInternMask", "TZ", "CG", "RectumMask", "SV", "NVB"]
  semi_supervision: True
  label_ratio: 0.10

MODEL:
  input: "img"
  multi_head: False
  reg: False
  keep_rate: 1
  warm_up_epoch: 500
  lr: 0.0005
  semi_co: 0.0005
